version: "3.3"

services:
  task_manager:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - {APP_PORT}:8000
    command: bash -c "uvicorn task_manager.main:app --host 0.0.0.0 --port 8000"
