name: linter-check

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install poetry
      - run: poetry install
      - run: poetry run flake8 task_manager
